spring:

  application:

    name: documenti-backend

  datasource:

    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/documenti_db
    username: documenti_user
    password: documenti_pass
    type: com.zaxxer.hikari.HikariDataSource

    hikari:

      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: documenti-pool


  liquibase:

    change-log: classpath:/migrations/changelog-master.yml
    database-change-log-lock-table: database_change_log_locking
    database-change-log-table: database_change_log

  batch:

    job:

      enabled: false

    initialize-schema: never

server:

  port: 8000

  servlet:

    context-path: /api

jwt:

  properties:

    header: Authorization
    secret-key: fnreskjdfn4p3ithn3q[04tfraf
    expires-at: 600

files:

  properties:

    storage-path: /home/andrey/temp
    validation-file-path: /validations/files/validation-config.xml


logging:

  config: classpath:logging/logback-spring.xml